name: HCCCE
version: @version@
main: at.helpch.hccce.HCCCE
api-version: 1.15.2
authors: [helpchat]
description: A community effort
website: https://helpch.at

commands:
  # jaims start
  ping:
    description: ping
  # jaims end

  # kali start
  online:
    description: get online player count
    # kali end